config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end
  root 'posts#index'

  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post, only: [:create, :destroy]

  def create
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

private
  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

private
  def post_params
    params.require(:post).permit(:title, :body)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_title"><%= time_ago_in_words(comment.created_at) %> ago</p>
  </div>

  <% if user_signed_in? %>
    <p><%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button",
                                                      data: { confirm: 'Are you sure?' } %></p>
  <% end %>

</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <br>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tumblr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="sidebar">
      <ul>
        <li class="category"><%= link_to "Tumblr", root_path %></li>
        <li><%= link_to "Posts", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>

      <% if !user_signed_in? %>
        <p class="sign_in"><%= link_to "User Login", new_user_session_path %></p>
      <% end %>

    </div>

    <div id="main_content">
      <div id="header">
        <% if current_page?(root_path) %>
          <p>Post Feed</p>
        <% elsif current_page?(about_path) %>
          <p>My Site</p>
        <% else %>
          <%= link_to "Back to Post Feed", root_path %>
        <% end %>

        <% if user_signed_in? %>
          <div class="buttons">
            <button class="button"><%= link_to "Make Post", new_post_path %></button>
            <button class="button"><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></button>
          </div>
        <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert") %>
      <% end %>

      <%= yield %>

    </div>

  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag "plumber.jpg" %>
  </div>

  <div id="content">
    <h1>It's Octocat dressed as a famous plumber Figure</h1>
    <p>Hi you know what my name is and I think I don't need any presentation, anyway ... ¡Here we
    goooo!<br><br>
    Mario (Japanese: マリオ Hepburn: Mario, pronounced [maɾi.o]; English: /ˈmɑːrioʊ, ˈmær-/, Italian:
    [ˈmaːrjo]) is a fictional character in the Mario video game franchise, owned by Nintendo and
    created by Japanese video game designer Shigeru Miyamoto. Acting as the company's mascot, as
    well as being the eponymous protagonist of the series, Mario has appeared in over 200 video
    games since his creation. Depicted as a short, pudgy, Italian plumber who resides in the
    Mushroom Kingdom, his adventures generally center upon rescuing Princess Peach from the Koopa
    villain Bowser. His fraternal twin brother and sidekick is Luigi.<br><br>
    With more than 500 million units sold worldwide, the overall Mario franchise is the best-selling
    video game franchise of all time.[1][2] Outside of the Super Mario platform series, other Mario
    genres include the Mario Kart racing series, sports games such as the Mario Tennis and Mario
    Golf series, role-playing games such as Mario & Luigi, Super Mario RPG and Paper Mario, and
    educational games such as Mario Is Missing!, Mario's Time Machine and Mario Teaches Typing.
    The franchise has branched into several media, including television shows, film, comics, and
    licensed merchandise. Since 1990, Mario has been voiced by Charles Martinet.</p>
  </div>
</div>

app/views/posts/_form.html.erb
  <%= form_for @post do |f| %>
    <% if @post.errors.any? %>
      <div id="errors">
        <h2><%= pluralize(@post.errors.count, "error") %> stopped this post from saving</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>

    <p>
      <%= f.submit %><br>
    </p>

  <% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Fixing a Post</h1>

  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"> <%= link_to post.title, post %></h2>
    <p class="body"><%= truncate(post.body, length: 100) %></p>
    <p class"date"> <%= time_ago_in_words(post.created_at) %> ago </p>
  </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>Make a Post</h1>

  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <%= @post.title %>
  </h1>

  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> ago

    <% if user_signed_in? %>
      <%= link_to '| Edit', edit_post_path(@post) %>
      <%= link_to '| Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure=' } %>
    <% end %>
  </p>

  <p class="body">
    <%= @post.body %>
  </p>

  <div id="comments">
    <h2><%= @post.comments.count %> comments for this post</h2>
    <%= render @post.comments %>
    <h3> Join Discussion: </h3>
    <%= render "comments/form" %>
  </div>
</div>